name: Release and Zip Code

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Extract version
        id: get_version
        run: echo "::set-output name=version::TEST"

      - name: Update XML attribute
        uses: Mudlet/xmlstarlet-action@master
        with:
          args: ed --inplace -u '/policyDefinitionms/@revision' -v "TESING" "./windows/firefox.admx"

      - name: Get filename
        id: get_filename
        run: echo "::set-output name=name::policy_templates_${{github.event.release.tag_name}}.zip"

      - name: Zip files
        run: |
          zip -r "${{ steps.get_filename.outputs.name }}" .

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./${{ steps.get_filename.outputs.name }}
          asset_name: ${{ steps.get_filename.outputs.name }}
          asset_content_type: application/zip
