name: Release and Zip Code

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Extract tag name
        id: extract_tag
        run: echo "::set-output name=tag::${GITHUB_REF#refs/tags/}"

      - name: Zip files
        run: |
          tag_name=$({{ steps.extract_tag.outputs.tag }})
          zip -r "${tag_name}.zip" .

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./${{ steps.extract_tag.outputs.tag }}.zip
          asset_name: ${{ steps.extract_tag.outputs.tag }}.zip
          asset_content_type: application/zip
