name: release
on:
  release:
    types: [published]
  workflow_dispatch:
jobs:
  build_release:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Get release
        id: get_release
        uses: bruceadams/get-release@v1.3.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: zip
        run: |
          zip -r foo.zip windows
      - name: upload extension file
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: ./foo.zip
          asset_name: foo.zip
          asset_content_type: application/zip
